# Generated by Django 4.0.6 on 2022-08-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=120)),
                ('receiver', models.CharField(max_length=120)),
                ('posting_division', models.CharField(max_length=120)),
                ('posting_department', models.CharField(max_length=120)),
                ('comment_division', models.CharField(max_length=120)),
                ('comment_department', models.CharField(max_length=120)),
                ('n', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
