# Generated by Django 4.0.6 on 2022-08-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnetwork',
            name='comment_department',
            field=models.CharField(choices=[('CPA', 'Cpa'), ('CPE', 'Cpe'), ('CPB', 'Cpb'), ('CPD', 'Cpd'), ('CPI', 'Cpi'), ('CPF', 'Cpf'), ('CPY', 'Cpy'), ('CPC', 'Cpc'), ('DDG', 'Ddg'), ('DDE', 'Dde'), ('DDJ', 'Ddj'), ('MEB', 'Meb')], max_length=120),
        ),
        migrations.AlterField(
            model_name='emailnetwork',
            name='comment_division',
            field=models.CharField(choices=[('Area Marketing Division', 'Amd'), ('Audit Division', 'Ad'), ('Sales & Distribution Division', 'Sdd'), ('Finance Division', 'Fd'), ('Corporate Communication Division', 'Ccd'), ('Strategic Marketing Division', 'Smd'), ('Media & Digital Business Division', 'Mdd'), ('Information System Division', 'Isd')], max_length=120),
        ),
        migrations.AlterField(
            model_name='emailnetwork',
            name='posting_department',
            field=models.CharField(choices=[('CPA', 'Cpa'), ('CPE', 'Cpe'), ('CPB', 'Cpb'), ('CPD', 'Cpd'), ('CPI', 'Cpi'), ('CPF', 'Cpf'), ('CPY', 'Cpy'), ('CPC', 'Cpc'), ('DDG', 'Ddg'), ('DDE', 'Dde'), ('DDJ', 'Ddj'), ('MEB', 'Meb')], max_length=120),
        ),
        migrations.AlterField(
            model_name='emailnetwork',
            name='posting_division',
            field=models.CharField(choices=[('Area Marketing Division', 'Amd'), ('Audit Division', 'Ad'), ('Sales & Distribution Division', 'Sdd'), ('Finance Division', 'Fd'), ('Corporate Communication Division', 'Ccd'), ('Strategic Marketing Division', 'Smd'), ('Media & Digital Business Division', 'Mdd'), ('Information System Division', 'Isd')], max_length=120),
        ),
    ]
