# Generated by Django 4.0.6 on 2022-08-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_network', '0002_alter_emailnetwork_comment_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnetwork',
            name='comment_division',
            field=models.CharField(choices=[('Area Marketing Division', 'Area Marketing Division'), ('Audit Division', 'Audit Division'), ('Sales & Distribution Division', 'Sales Distribution Division'), ('Finance Division', 'Finance Division'), ('Corporate Communication Division', 'Corporate Communication Division'), ('Strategic Marketing Division', 'Strategic Marketing Division'), ('Media & Digital Business Division', 'Media Digital Business Division'), ('Information System Division', 'Information System Division')], max_length=120),
        ),
        migrations.AlterField(
            model_name='emailnetwork',
            name='posting_division',
            field=models.CharField(choices=[('Area Marketing Division', 'Area Marketing Division'), ('Audit Division', 'Audit Division'), ('Sales & Distribution Division', 'Sales Distribution Division'), ('Finance Division', 'Finance Division'), ('Corporate Communication Division', 'Corporate Communication Division'), ('Strategic Marketing Division', 'Strategic Marketing Division'), ('Media & Digital Business Division', 'Media Digital Business Division'), ('Information System Division', 'Information System Division')], max_length=120),
        ),
    ]
